version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_REPO: ${GIT_REPO:-https://github.com/AlexandreMonchain/Passphrase.git}
        GIT_BRANCH: ${GIT_BRANCH:-dev}
    container_name: passphrase-web
    environment:
      APP_ENV: ${APP_ENV:-prod}
      APP_DEBUG: ${APP_DEBUG:-0}
    volumes:
      - app_cache:/app/var/cache
      - app_logs:/app/var/log
    ports:
      - "8000:80"
    restart: unless-stopped

volumes:
  app_cache:
  app_logs:
